<?php

use Illuminate\Database\Seeder;
use \App\Models\persona;

class personasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      DB::statement('set foreign_key_checks = 0;');
      DB::table('persona')->truncate();
      DB::statement('set foreign_key_checks = 1;');

        $persona= new persona();
        $persona->rol='alumno';
        $persona->nombres='Pepe';
        $persona->apaterno='Robles';
        $persona->amaterno='Padilla';
        $persona->curp='xxxxxxxxxxxxxxxxxx';
        $persona->fnaci='1996-12-12';
        $persona->sexo='M';
        $persona->email='Pepe@example.example.com';
        $persona->calle='Pino Suarez';
        $persona->num_int='43';
        $persona->num_ext='10';
        $persona->colonia='Cantera';
        $persona->codigo_postal='58023';
        $persona->ciudad='Morelia';
        $persona->estado='Michoacan';
        $persona->num_tel='443333333';
        $persona->num_cel='443412121';
        $persona->imagen='jumtest.jpg';
        $persona->save();

        $persona= new persona();
        $persona->rol='Admin';
        $persona->nombres='Diego';
        $persona->apaterno='Ramirez';
        $persona->amaterno='Rodriguez';
        $persona->fnaci='1997-12-12';
        $persona->curp='xxxxxxxxxxxxxxxxxy';
        $persona->sexo='M';
        $persona->email='Diego@example.example.com';
        $persona->calle='Pino Suarez';
        $persona->num_int='44';
        $persona->num_ext='18';
        $persona->colonia='Cantera';
        $persona->codigo_postal='58023';
        $persona->ciudad='Morelia';
        $persona->estado='Michoacan';
        $persona->num_tel='443333333';
        $persona->num_cel='443412121';
        $persona->imagen='jumtest.jpg';
        $persona->save();

        $persona= new persona();
        $persona->rol='Admin';
        $persona->nombres='Roberto';
        $persona->apaterno='Gonzalez';
        $persona->amaterno='Rodriguez';
        $persona->fnaci='1992-7-10';
        $persona->curp='xxxxxxxxxxxxxxxxyy';
        $persona->sexo='M';
        $persona->email='roberto@example.example.com';
        $persona->calle='Mango';
        $persona->num_int='4';
        $persona->num_ext='19';
        $persona->colonia='Xangari';
        $persona->codigo_postal='58058';
        $persona->ciudad='Morelia';
        $persona->estado='Michoacan';
        $persona->num_tel='443223233';
        $persona->num_cel='443444121';
        $persona->imagen='jumtest.jpg';
        $persona->save();


        $persona= new persona();
        $persona->rol='Prof';
        $persona->nombres='Nancy';
        $persona->apaterno='Martinez';
        $persona->amaterno='Gil';
        $persona->fnaci='1994-7-10';
        $persona->curp='xxxxxxxxxxxxxxxyyy';
        $persona->sexo='F';
        $persona->email='nancy@example.example.com';
        $persona->calle='Ruby';
        $persona->num_int='3';
        $persona->num_ext='19';
        $persona->colonia='On Rails';
        $persona->codigo_postal='58010';
        $persona->ciudad='Morelia';
        $persona->estado='Michoacan';
        $persona->num_tel='443223233';
        $persona->num_cel='443444121';
        $persona->imagen='jumtest.jpg';
        $persona->save();

        $persona= new persona();
        $persona->rol='Prof';
        $persona->nombres='Rubén';
        $persona->apaterno='Regil';
        $persona->amaterno='Tecla';
        $persona->fnaci='1994-7-10';
        $persona->curp='xxxxxxxxxxxxxxyyyy';
        $persona->sexo='M';
        $persona->email='ruby@example.example.com';
        $persona->calle='Parangaricutirimicuaro';
        $persona->num_int='56';
        $persona->num_ext='91';
        $persona->colonia='Mexico';
        $persona->codigo_postal='58013';
        $persona->ciudad='Morelia';
        $persona->estado='Michoacan';
        $persona->num_tel='443223233';
        $persona->num_cel='443444121';
        $persona->imagen='jumtest.jpg';
        $persona->save();

        $persona= new persona();
        $persona->rol='Coord';
        $persona->nombres='Monica';
        $persona->apaterno='Mordisco';
        $persona->amaterno='Gomez';
        $persona->fnaci='1970-1-4';
        $persona->curp='xxxxxxxxxxxxxyyyyy';
        $persona->sexo='F';
        $persona->email='moni@example.example.com';
        $persona->calle='Fuerza';
        $persona->num_int='134';
        $persona->num_ext='8';
        $persona->colonia='Mexico';
        $persona->codigo_postal='58016';
        $persona->ciudad='Morelia';
        $persona->estado='Michoacan';
        $persona->num_tel='443223233';
        $persona->num_cel='443444121';
        $persona->imagen='jumtest.jpg';
        $persona->save();

        $persona= new persona();
        $persona->rol='Coord';
        $persona->nombres='Nelly';
        $persona->apaterno='Aguilar';
        $persona->amaterno='Ramirez';
        $persona->fnaci='1964-6-4';
        $persona->curp='xxxxxxxxxxxxyyyyyy';
        $persona->sexo='F';
        $persona->email='nelly@example.example.com';
        $persona->calle='Gloria';
        $persona->num_int='14';
        $persona->num_ext='56';
        $persona->colonia='Mexico';
        $persona->codigo_postal='56016';
        $persona->ciudad='Morelia';
        $persona->estado='Michoacan';
        $persona->num_tel='443223233';
        $persona->num_cel='443444121';
        $persona->imagen='jumtest.jpg';
        $persona->save();

        $persona= new persona();
        $persona->rol='alumno';
        $persona->nombres='Javier';
        $persona->apaterno='Perez';
        $persona->amaterno='Santos';
        $persona->curp='yyxxxxxxxxxxxxxxxx';
        $persona->fnaci='1996-8-12';
        $persona->sexo='M';
        $persona->email='Javier@example.example.com';
        $persona->calle='Independencia';
        $persona->num_int='503';
        $persona->num_ext='503';
        $persona->colonia='Revolucion';
        $persona->codigo_postal='58337';
        $persona->ciudad='Morelia';
        $persona->estado='Michoacan';
        $persona->num_tel='443321313';
        $persona->num_cel='443321121';
        $persona->imagen='jumtest.jpg';
        $persona->save();

        $persona= new persona();
        $persona->rol='Alumno';
        $persona->nombres='Pepillo';
        $persona->apaterno='Robledo';
        $persona->amaterno='Padillon';
        $persona->curp='xxxxxxxxxqwxxxxxxx';
        $persona->fnaci='1996-12-11';
        $persona->sexo='M';
        $persona->email='Pepe@example.com';
        $persona->calle='Pinol Suarez';
        $persona->num_int='12';
        $persona->num_ext='10';
        $persona->colonia='Cantera';
        $persona->codigo_postal='58023';
        $persona->ciudad='Morelia';
        $persona->estado='Michoacan';
        $persona->num_tel='443333333';
        $persona->num_cel='443412121';
        $persona->imagen='jumtest.jpg';
        $persona->save();

        $persona= new persona();
        $persona->rol='Alumno';
        $persona->nombres='Eduardo';
        $persona->apaterno='Gonzales';
        $persona->amaterno='Padilla';
        $persona->curp='xxxxxxxxaswxxxxxxx';
        $persona->fnaci='1996-12-11';
        $persona->sexo='M';
        $persona->email='Pepe@example.com';
        $persona->calle='Pinol Suarez';
        $persona->num_int='12';
        $persona->num_ext='10';
        $persona->colonia='Cantera';
        $persona->codigo_postal='58023';
        $persona->ciudad='Morelia';
        $persona->estado='Michoacan';
        $persona->num_tel='443333333';
        $persona->num_cel='443412121';
        $persona->imagen='jumtest.jpg';
        $persona->save();


        $persona= new persona();
        $persona->rol='Alumno';
        $persona->nombres='Raul';
        $persona->apaterno='Gonz';
        $persona->amaterno='Lopez';
        $persona->curp='xxxxxxxxpowxxxxxxx';
        $persona->fnaci='1996-12-11';
        $persona->sexo='M';
        $persona->email='Pepe@example.com';
        $persona->calle='Pinol Suarez';
        $persona->num_int='12';
        $persona->num_ext='10';
        $persona->colonia='Cantera';
        $persona->codigo_postal='58023';
        $persona->ciudad='Morelia';
        $persona->estado='Michoacan';
        $persona->num_tel='443333333';
        $persona->num_cel='443412121';
        $persona->imagen='jumtest.jpg';
        $persona->save();


        $persona= new persona();
        $persona->rol='Alumno';
        $persona->nombres='Raule';
        $persona->apaterno='Sean';
        $persona->amaterno='Ibarra';
        $persona->curp='xxxaaxxxpowxxxxxxx';
        $persona->fnaci='1996-12-11';
        $persona->sexo='M';
        $persona->email='Pepe@example.com';
        $persona->calle='Pinol Suarez';
        $persona->num_int='12';
        $persona->num_ext='10';
        $persona->colonia='Cantera';
        $persona->codigo_postal='58023';
        $persona->ciudad='Morelia';
        $persona->estado='Michoacan';
        $persona->num_tel='443333333';
        $persona->num_cel='443412121';
        $persona->imagen='jumtest.jpg';
        $persona->save();


        $persona= new persona();
        $persona->rol='Alumno';
        $persona->nombres='Jaye';
        $persona->apaterno='Sean';
        $persona->amaterno='Lopez';
        $persona->curp='xxxaaopxpowxxxxxxx';
        $persona->fnaci='1996-12-11';
        $persona->sexo='M';
        $persona->email='Pepe@example.com';
        $persona->calle='Pinol Suarez';
        $persona->num_int='12';
        $persona->num_ext='10';
        $persona->colonia='Cantera';
        $persona->codigo_postal='58023';
        $persona->ciudad='Morelia';
        $persona->estado='Michoacan';
        $persona->num_tel='443333333';
        $persona->num_cel='443412121';
        $persona->imagen='jumtest.jpg';
        $persona->save();


        $persona= new persona();
        $persona->rol='Alumno';
        $persona->nombres='Jose';
        $persona->apaterno='Rayon';
        $persona->amaterno='Lopez';
        $persona->curp='xxxaaopxpowxloxxxx';
        $persona->fnaci='1996-12-11';
        $persona->sexo='M';
        $persona->email='Pepe@example.com';
        $persona->calle='Pinol Suarez';
        $persona->num_int='12';
        $persona->num_ext='10';
        $persona->colonia='Cantera';
        $persona->codigo_postal='58023';
        $persona->ciudad='Morelia';
        $persona->estado='Michoacan';
        $persona->num_tel='443333333';
        $persona->num_cel='443412121';
        $persona->imagen='jumtest.jpg';
        $persona->save();

        $persona= new persona();
        $persona->rol='Alumno';
        $persona->nombres='Raymundo';
        $persona->apaterno='Martinez';
        $persona->amaterno='Luz';
        $persona->curp='yuxaaopxpowxloxxxx';
        $persona->fnaci='1996-12-11';
        $persona->sexo='M';
        $persona->email='Pepe@example.com';
        $persona->calle='Pinol Suarez';
        $persona->num_int='12';
        $persona->num_ext='10';
        $persona->colonia='Cantera';
        $persona->codigo_postal='58023';
        $persona->ciudad='Morelia';
        $persona->estado='Michoacan';
        $persona->num_tel='443333333';
        $persona->num_cel='443412121';
        $persona->imagen='jumtest.jpg';
        $persona->save();

        $persona= new persona();
        $persona->rol='Alumno';
        $persona->nombres='Maria';
        $persona->apaterno='Aguilar';
        $persona->amaterno='Luz';
        $persona->curp='yuxaaopxpowxlouyxx';
        $persona->fnaci='1996-12-11';
        $persona->sexo='F';
        $persona->email='Pepe@example.com';
        $persona->calle='Pinol Suarez';
        $persona->num_int='12';
        $persona->num_ext='10';
        $persona->colonia='Cantera';
        $persona->codigo_postal='58023';
        $persona->ciudad='Morelia';
        $persona->estado='Michoacan';
        $persona->num_tel='443333333';
        $persona->num_cel='443412121';
        $persona->imagen='jumtest.jpg';
        $persona->save();

        $persona= new persona();
        $persona->rol='Alumno';
        $persona->nombres='Guadalupe';
        $persona->apaterno='Martinez';
        $persona->amaterno='Luz';
        $persona->curp='yuxaaoerpowxloxxxx';
        $persona->fnaci='1996-12-11';
        $persona->sexo='F';
        $persona->email='Pepe@example.com';
        $persona->calle='Pinol Suarez';
        $persona->num_int='12';
        $persona->num_ext='10';
        $persona->colonia='Cantera';
        $persona->codigo_postal='58023';
        $persona->ciudad='Morelia';
        $persona->estado='Michoacan';
        $persona->num_tel='443333333';
        $persona->num_cel='443412121';
        $persona->imagen='jumtest.jpg';
        $persona->save();

        $persona= new persona();
        $persona->rol='Alumno';
        $persona->nombres='Luis';
        $persona->apaterno='Garcia';
        $persona->amaterno='Luz';
        $persona->curp='yuxaaolopowxloxxxx';
        $persona->fnaci='1996-12-11';
        $persona->sexo='M';
        $persona->email='Pepe@example.com';
        $persona->calle='Pinol Suarez';
        $persona->num_int='12';
        $persona->num_ext='10';
        $persona->colonia='Cantera';
        $persona->codigo_postal='58023';
        $persona->ciudad='Morelia';
        $persona->estado='Michoacan';
        $persona->num_tel='443333333';
        $persona->num_cel='443412121';
        $persona->imagen='jumtest.jpg';
        $persona->save();

        $persona= new persona();
        $persona->rol='Alumno';
        $persona->nombres='Ema';
        $persona->apaterno='Rumbo';
        $persona->amaterno='Perez';
        $persona->curp='yuxaaoerpowxloxbvx';
        $persona->fnaci='1996-12-11';
        $persona->sexo='F';
        $persona->email='Pepe@example.com';
        $persona->calle='Pinol Suarez';
        $persona->num_int='12';
        $persona->num_ext='10';
        $persona->colonia='Cantera';
        $persona->codigo_postal='58023';
        $persona->ciudad='Morelia';
        $persona->estado='Michoacan';
        $persona->num_tel='443333333';
        $persona->num_cel='443412121';
        $persona->imagen='jumtest.jpg';
        $persona->save();

        $persona= new persona();
        $persona->rol='Alumno';
        $persona->nombres='Emiliano';
        $persona->apaterno='Ibarra';
        $persona->amaterno='Bejar';
        $persona->curp='yuxapoerpowxloxxxx';
        $persona->fnaci='1996-12-11';
        $persona->sexo='M';
        $persona->email='Pepe@example.com';
        $persona->calle='Pinol Suarez';
        $persona->num_int='12';
        $persona->num_ext='10';
        $persona->colonia='Cantera';
        $persona->codigo_postal='58023';
        $persona->ciudad='Morelia';
        $persona->estado='Michoacan';
        $persona->num_tel='443333333';
        $persona->num_cel='443412121';
        $persona->imagen='jumtest.jpg';
        $persona->save();

        $persona= new persona();
        $persona->rol='Alumno';
        $persona->nombres='Diego';
        $persona->apaterno='Galeana';
        $persona->amaterno='Luz';
        $persona->curp='yuxaayurpowxloxxxx';
        $persona->fnaci='1996-12-11';
        $persona->sexo='M';
        $persona->email='Pepe@example.com';
        $persona->calle='Pinol Suarez';
        $persona->num_int='12';
        $persona->num_ext='10';
        $persona->colonia='Cantera';
        $persona->codigo_postal='58023';
        $persona->ciudad='Morelia';
        $persona->estado='Michoacan';
        $persona->num_tel='443333333';
        $persona->num_cel='443412121';
        $persona->imagen='jumtest.jpg';
        $persona->save();

        $persona= new persona();
        $persona->rol='Alumno';
        $persona->nombres='Mina';
        $persona->apaterno='Galeana';
        $persona->amaterno='Luz';
        $persona->curp='yuxaaoerpowxaoxwex';
        $persona->fnaci='1996-12-11';
        $persona->sexo='F';
        $persona->email='Pepe@example.com';
        $persona->calle='Pinol Suarez';
        $persona->num_int='12';
        $persona->num_ext='10';
        $persona->colonia='Cantera';
        $persona->codigo_postal='58023';
        $persona->ciudad='Morelia';
        $persona->estado='Michoacan';
        $persona->num_tel='443333333';
        $persona->num_cel='443412121';
        $persona->imagen='jumtest.jpg';
        $persona->save();

        $persona= new persona();
        $persona->rol='Alumno';
        $persona->nombres='Patricia';
        $persona->apaterno='Luz';
        $persona->amaterno='Aguilar';
        $persona->curp='yuxaaoerpowxloxwex';
        $persona->fnaci='1996-12-11';
        $persona->sexo='F';
        $persona->email='Pepe@example.com';
        $persona->calle='Pinol Suarez';
        $persona->num_int='12';
        $persona->num_ext='10';
        $persona->colonia='Cantera';
        $persona->codigo_postal='58023';
        $persona->ciudad='Morelia';
        $persona->estado='Michoacan';
        $persona->num_tel='443333333';
        $persona->num_cel='443412121';
        $persona->imagen='jumtest.jpg';
        $persona->save();

        $persona= new persona();
        $persona->rol='Alumno';
        $persona->nombres='Paulino';
        $persona->apaterno='Rivas';
        $persona->amaterno='Perez';
        $persona->curp='yuxaaosspowxloxwex';
        $persona->fnaci='1996-12-11';
        $persona->sexo='M';
        $persona->email='Pepe@example.com';
        $persona->calle='Pinol Suarez';
        $persona->num_int='12';
        $persona->num_ext='10';
        $persona->colonia='Cantera';
        $persona->codigo_postal='58023';
        $persona->ciudad='Morelia';
        $persona->estado='Michoacan';
        $persona->num_tel='443333333';
        $persona->num_cel='443412121';
        $persona->imagen='jumtest.jpg';
        $persona->save();

        $persona= new persona();
        $persona->rol='Alumno';
        $persona->nombres='Terry';
        $persona->apaterno='Johnson';
        $persona->amaterno='Gonzales';
        $persona->curp='yuxaaeporneroxwex';
        $persona->fnaci='1996-12-11';
        $persona->sexo='M';
        $persona->email='Pepe@example.com';
        $persona->calle='Pinol Suarez';
        $persona->num_int='12';
        $persona->num_ext='10';
        $persona->colonia='Cantera';
        $persona->codigo_postal='58023';
        $persona->ciudad='Morelia';
        $persona->estado='Michoacan';
        $persona->num_tel='443333333';
        $persona->num_cel='443412121';
        $persona->imagen='jumtest.jpg';
        $persona->save();

        $persona= new persona();
        $persona->rol='Alumno';
        $persona->nombres='Cassandra';
        $persona->apaterno='Werever';
        $persona->amaterno='Tumorrow';
        $persona->curp='yuxaaeosrnroxwex';
        $persona->fnaci='1996-12-11';
        $persona->sexo='F';
        $persona->email='Pepe@example.com';
        $persona->calle='Pinol Suarez';
        $persona->num_int='12';
        $persona->num_ext='10';
        $persona->colonia='Cantera';
        $persona->codigo_postal='58023';
        $persona->ciudad='Morelia';
        $persona->estado='Michoacan';
        $persona->num_tel='443333333';
        $persona->num_cel='443412121';
        $persona->imagen='jumtest.jpg';
        $persona->save();

        $persona= new persona();
        $persona->rol='Alumno';
        $persona->nombres='Sandro';
        $persona->apaterno='Zavala';
        $persona->amaterno='Suarez';
        $persona->curp='yuxarnosrnroxwex';
        $persona->fnaci='1996-12-11';
        $persona->sexo='M';
        $persona->email='Pepe@example.com';
        $persona->calle='Pinol Suarez';
        $persona->num_int='12';
        $persona->num_ext='10';
        $persona->colonia='Cantera';
        $persona->codigo_postal='58023';
        $persona->ciudad='Morelia';
        $persona->estado='Michoacan';
        $persona->num_tel='443333333';
        $persona->num_cel='443412121';
        $persona->imagen='jumtest.jpg';
        $persona->save();

        $persona= new persona();
        $persona->rol='Alumno';
        $persona->nombres='Alejandro';
        $persona->apaterno='Elma';
        $persona->amaterno='Canon';
        $persona->curp='yuxarnosrwerowex';
        $persona->fnaci='1996-12-11';
        $persona->sexo='M';
        $persona->email='Pepe@example.com';
        $persona->calle='Pinol Suarez';
        $persona->num_int='12';
        $persona->num_ext='10';
        $persona->colonia='Cantera';
        $persona->codigo_postal='58023';
        $persona->ciudad='Morelia';
        $persona->estado='Michoacan';
        $persona->num_tel='443333333';
        $persona->num_cel='443412121';
        $persona->imagen='jumtest.jpg';
        $persona->save();


        $persona= new persona();
        $persona->rol='Alumno';
        $persona->nombres='Linsko';
        $persona->apaterno='Soas';
        $persona->amaterno='Caps';
        $persona->curp='yuxarnwewerrowex';
        $persona->fnaci='1996-12-11';
        $persona->sexo='M';
        $persona->email='Pepe@example.com';
        $persona->calle='Pinol Suarez';
        $persona->num_int='12';
        $persona->num_ext='10';
        $persona->colonia='Cantera';
        $persona->codigo_postal='58023';
        $persona->ciudad='Morelia';
        $persona->estado='Michoacan';
        $persona->num_tel='443333333';
        $persona->num_cel='443412121';
        $persona->imagen='jumtest.jpg';
        $persona->save();

        $persona= new persona();
        $persona->rol='Alumno';
        $persona->nombres='Badabbum';
        $persona->apaterno='Vega';
        $persona->amaterno='Pinol';
        $persona->curp='yuxarnoaatsmrowex';
        $persona->fnaci='1996-12-11';
        $persona->sexo='M';
        $persona->email='Pepe@example.com';
        $persona->calle='Pinol Suarez';
        $persona->num_int='12';
        $persona->num_ext='10';
        $persona->colonia='Cantera';
        $persona->codigo_postal='58023';
        $persona->ciudad='Morelia';
        $persona->estado='Michoacan';
        $persona->num_tel='443333333';
        $persona->num_cel='443412121';
        $persona->imagen='jumtest.jpg';
        $persona->save();






    }
}
